[workspace]
resolver = "2"
members = ["swarm-lib"]


[profile.release]
debug = true


[workspace.dependencies]
bevy = { version = "0.15.0", features = ["2d", "2d_ui"] }
bevy_ecs_tilemap = "0.15.0"
thiserror = "2.0"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"