max_width = 80
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
reorder_imports = true
format_strings = true
wrap_comments = true
comment_width = 80
normalize_comments = true
format_code_in_doc_comments = true
